spring.application.name=gerenciador-projetos

spring.datasource.url=jdbc:postgresql://localhost:5432/gerenciador_projetos_db
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# JWT
#jwt.secret=0
#jwt.expirationInMinutes=15

# Logging Configuration
logging.level.root=INFO
#logging.level.br.com.tarishenrique.sistema=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.type=TRACE
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n


springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true